# Generated by Django 2.2.12 on 2023-06-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intention',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hi AI'), (2, 'Goodbye'), (3, 'Good night'), (4, 'Information')], null=True),
        ),
    ]
