# Generated by Django 2.2.12 on 2023-06-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intention', '0003_auto_20230625_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hi AI'), (2, 'Goodbye'), (3, 'Good night'), (4, 'Information'), (7, 'Confirmation'), (8, 'Negation'), (9, 'Farewell'), (10, 'Create'), (11, 'Create Knowledge Base')], null=True),
        ),
    ]
