# Generated by Django 2.2.12 on 2023-07-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intention', '0006_auto_20230702_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='type',
            field=models.IntegerField(choices=[(1, 'Hi AI'), (2, 'Goodbye'), (3, 'Good night'), (4, 'What Information Want'), (5, 'I Need Information'), (7, 'Confirmation'), (8, 'Negation'), (9, 'Farewell'), (10, 'Create Intention'), (11, 'Adding New Knowledge'), (12, 'What Type Intenton')], null=True),
        ),
    ]
