# Generated by Django 2.2.12 on 2023-06-25 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intention', '0002_intention_type'),
        ('vocabulary', '0002_auto_20230625_0352'),
        ('knowledge_base', '0001_initial'),
        ('dialog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogquestion',
            name='vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialogs_question', to='vocabulary.Vocabulary'),
        ),
        migrations.AddField(
            model_name='dialogresponse',
            name='intention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialogs_response', to='intention.Intention'),
        ),
        migrations.AddField(
            model_name='dialogresponse',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialogs_response', to='knowledge_base.KnowledgeBase'),
        ),
    ]
