# Generated by Django 2.2.12 on 2023-06-25 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0002_auto_20230625_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogquestion',
            name='dialog_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dialogs_question', to='dialog.DialogResponse'),
        ),
    ]
