# Generated by Django 2.2.12 on 2023-06-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0004_auto_20230625_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialog',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
