# Generated by Django 2.2.12 on 2023-06-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0005_dialog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogcommand',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dialogquestion',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dialogresponse',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
