# Generated by Django 2.2.12 on 2023-06-26 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0006_auto_20230625_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialogresponse',
            name='dialog_command',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_response', to='dialog.DialogCommand'),
        ),
        migrations.AlterField(
            model_name='dialogresponse',
            name='dialog_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_response', to='dialog.DialogQuestion'),
        ),
    ]
