# Generated by Django 2.2.12 on 2023-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0007_auto_20230626_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialog',
            name='dialogs',
            field=models.ManyToManyField(blank=True, related_name='_dialog_dialogs_+', to='dialog.Dialog'),
        ),
    ]
