# Generated by Django 2.2.12 on 2023-07-03 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialog', '0009_auto_20230629_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialogresponse',
            name='dialog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dialogs_response', to='dialog.Dialog'),
        ),
    ]
