# Generated by Django 2.2.12 on 2023-06-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intention', '0002_intention_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('intentions', models.ManyToManyField(related_name='knowledge_bases', to='intention.Intention')),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Bases',
                'db_table': 'knowledge_base',
            },
        ),
    ]
